version: '3.7'

services:
    redis:
      container_name: Flask_ReactSSE_redis
      image: redis

    server:
      container_name: Flask_ReactSSE_server
      build:
        context: .
        dockerfile: Server/Dockerfile
      volumes:
        - './Server:/Server'
      ports:
        - '5000:5000'
      # expose:
      #  - 5000
      depends_on:
        - redis 

    client:
      container_name: Flask_ReactSSE_client
      build:
        context: .
        dockerfile: Client/Dockerfile
      volumes:
        - './Client:/Client'
      ports:
        - '3000:3000'
      # expose:
      #  - 3000
      depends_on:
        - server
 